name: ğŸ¤– Sync to Gitee Mirror

on: [page_build, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ” Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # æ³¨æ„åœ¨ Settings->Secrets é…ç½® GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ GitHub æºä»“åº“åœ°å€
          source-repo: git@github.com:visiky/resume.git
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ç›®æ ‡ä»“åº“åœ°å€
          destination-repo: git@gitee.com:visiky/resume.git

      - name: âœ… Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ç”¨æˆ·å
          gitee-username: visiky
          # æ³¨æ„åœ¨ Settings->Secrets é…ç½® GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # å‚æ•°é»˜è®¤æ˜¯ masterï¼Œè‹¥æ˜¯å…¶ä»–åˆ†æ”¯ï¼Œéœ€è¦æŒ‡å®š
          branch: gh-pages
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ä»“åº“
          gitee-repo: visiky/resume
