name: DingTalk Release Notify

on:
  workflow_dispatch:
  release:
    types: [published, edited]

jobs:
  release-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: visiky/release-notify@main
        with:
          DING_TALK_TOKEN: ${{ secrets.DING_TALK_TOKEN}}
          notify_title: 'ðŸŽ‰ Resume release {release_tag} ðŸŽ‰'
          notify_body: 'æµ‹è¯• G2'
          notify_footer: ''
          at_all: false
